// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYBF0i2XMALzk8oPAQO1aLBMD-m8IQNTo',
    appId: '1:330105408946:web:a1d8d9935c7442fd5028ab',
    messagingSenderId: '330105408946',
    projectId: 'cozy-meal',
    authDomain: 'cozy-meal.firebaseapp.com',
    storageBucket: 'cozy-meal.appspot.com',
    measurementId: 'G-VVV3GX4JYS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJv4hc0TJWYHAibV4SZdvZBqn5FiGtwMw',
    appId: '1:330105408946:android:7cf083647a8f11075028ab',
    messagingSenderId: '330105408946',
    projectId: 'cozy-meal',
    storageBucket: 'cozy-meal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxUDhUAxn474iXz0MsqjXz-c8XzbqQhC4',
    appId: '1:330105408946:ios:b65cbd3e0f576bbe5028ab',
    messagingSenderId: '330105408946',
    projectId: 'cozy-meal',
    storageBucket: 'cozy-meal.appspot.com',
    iosClientId: '330105408946-ibvie0cfl2lvvq616nudah44s6bmvb1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.cozyMeal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxUDhUAxn474iXz0MsqjXz-c8XzbqQhC4',
    appId: '1:330105408946:ios:b65cbd3e0f576bbe5028ab',
    messagingSenderId: '330105408946',
    projectId: 'cozy-meal',
    storageBucket: 'cozy-meal.appspot.com',
    iosClientId: '330105408946-ibvie0cfl2lvvq616nudah44s6bmvb1m.apps.googleusercontent.com',
    iosBundleId: 'com.example.cozyMeal',
  );
}
